The following ABNF grammar defines the zproto example protocol:

    zproto_example  = *( C:log | C:structures | C:binary )

    C:log           = signature %d1 sequence level event node peer time data
    signature       = %xAA %d0              ; two octets
    sequence        = number-2              ; 
    level           = number-1              ; Log severity level
    event           = number-1              ; Type of event
    node            = number-2              ; Sending node
    peer            = number-2              ; Refers to this peer
    time            = number-8              ; Log date/time
    data            = string-2              ; Actual log message

    C:structures    = signature %d2 sequence aliases headers
    sequence        = number-2              ; 
    aliases         = strings               ; List of strings
    headers         = dictionary            ; Other random properties

    C:binary        = signature %d3 sequence flags address content
    sequence        = number-2              ; 
    flags           = 4OCTET                ; A set of flags
    address         = frame                 ; Return address as frame
    content         = msg                   ; Message to be delivered

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-2        = 2OCTET
    number-4        = 4OCTET
    number-8        = 8OCTET                
    
    ; Strings are always length + contents
    string-1        = number-1 *VCHAR
    string-2        = number-2 *VCHAR
    string-4        = number-4 *VCHAR
    string-8        = number-8 *VCHAR       

    ; A list of string values
    strings         = count *value
    value           = string-1

    ; A list of name/value pairs
    dictionary      = count *name-value
    count           = number-1
    name-value       = string-1             ; "name=value"

    ; A frame is zero or more octets encoded as a ZeroMQ frame
    frame           = *OCTET                

    ; A msg is zero or more distinct frames
    msg             = *frame
