The following ABNF grammar defines the zproto example protocol:

    example         = log | structures | binary

    ; Log an event.
    C:log           = signature %d1 version level event node peer time host data
    signature       = %xAA %d0              ; two octets
    version         = number-2              ; Version
    level           = number-1              ; Log severity level
    event           = number-1              ; Type of event
    node            = number-2              ; Sending node
    peer            = number-2              ; Refers to this peer
    time            = number-8              ; Log date/time
    host            = string                ; Originating hostname
    data            = longstr               ; Actual log message

    ; This message contains a list and a hash.
    C:structures    = signature %d2 aliases headers
    aliases         = strings               ; List of strings
    headers         = dictionary            ; Other random properties

    ; Deliver a multi-part message.
    C:binary        = signature %d3 flags public key address content
    flags           = 4OCTET                ; A set of flags
    public key      = chunk                 ; Our public key
    address         = frame                 ; Return address as frame
    content         = msg                   ; Message to be delivered

    ; Demonstrate custom-defined types
    C:types         = signature %d4 client supplier
    client          = person                ; Client contact
    supplier        = person                ; Supplier contact
    person          = forename surname mobile email
    forename        = string                ; Given name
    surname         = string                ; Family name
    mobile          = string                ; Mobile phone number
    email           = string                ; Email address

    ; Demonstrates repeating fields
    C:repeat        = signature %d5 no1 no2 no4 no8 str lstr strs chunks persons
    no1             = 0*3number-1                          ; Repeating byte
    no2             = 0*144number-2                        ; Repeating 2-bytes
    no4             = 0*256number-4                        ; Repeating 4-bytes
    no8             = *number-8                            ; Repeating 8-bytes
    str             = 0*3string                            ; Repeating 1-byte string
    lstr            = *longstr                             ; Repeating 4-byte string
    strs            = *strings                             ; Repeating strings
    chunks          = 0*2chunk                             ; Repeating chunks
    persons         = *person                              ; Repeating person

    ; A list of string values
    strings         = strings-count *strings-value
    strings-count   = number-4
    strings-value   = longstr

    ; A list of name/value pairs
    dictionary      = dict-count *( dict-name dict-value )
    dict-count      = number-4
    dict-value      = longstr
    dict-name       = string

    ; A chunk has 4-octet length + binary contents
    chunk           = number-4 *OCTET

    ; A frame is zero or more octets encoded as a ZeroMQ frame
    frame           = *OCTET

    ; A msg is zero or more distinct frames
    msg             = *frame

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-2        = 2OCTET
    number-4        = 4OCTET
    number-8        = 8OCTET
